JoraSFDC/src/objects/Physician__c.object
<CustomObject>
    <fields>
        <fullName>Google_Calendar_Link__c</fullName>
        <label>Google Calendar Link</label>
        <type>Url</type>
    </fields>
    <label>Physician</label>
    <nameField>
        <label>Physician Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Physicians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

JoraSFDC/src/classes/AppointmentGoogleEmbed.cls
public class AppointmentGoogleEmbed{

    public List<SelectOption> PhysiciansCalendars {get;set;}
     public String selectedCalendar{get;set;}
    
 
 public AppointmentGoogleEmbed(){
  PhysiciansCalendars = new List<SelectOption>();
    PhysiciansCalendars.add(new SelectOption('','--None--'));
    list<Physician__c> Phs =  [select Google_Calendar_Link__c, name from Physician__c where Google_Calendar_Link__c!=null];
     for(Physician__c ph:Phs)
     {
     PhysiciansCalendars.add(new SelectOption(ph.Google_Calendar_Link__c, ph.Name));
     }
     
 
}
}